# -*- coding: utf-8 -*-
"""task1-harini.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZfSzCwxTB7wXsPweqIN_5MVPlj88hhl
"""

#load data set
import pandas as pd
df = pd.read_csv('/content/disney_plus_titles.csv')

#view basic dataset
df.head()
df.info()

#handle missing values
# Check how many missing values are in each column
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

# show only columns with missing values
print("\nColumns with missing values:\n", missing_values[missing_values > 0])

# Fill missing values for specific columns
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

# Drop rows if critical fields are missing
df.dropna(subset=['title'], inplace=True)

df = df.drop_duplicates()

# Standardize column values (e.g., 'type' and 'country')
df['type'] = df['type'].str.lower().str.strip()
df['country'] = df['country'].str.title().str.strip()

# Convert 'date_added' to datetime format
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

# Make all column names lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')
print(df.columns)

#save
df.to_csv('cleaned_disney_plus.csv', index=False)